/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mynews.ui;

/**
 *
 * @author RESEARCH2
 */
public class JPanelGreenPolicy extends javax.swing.JPanel {

  // private JPanelWrapper wrapper;
    public JPanelGreenPolicy() {
        initComponents();
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        webLabel4 = new com.alee.laf.label.WebLabel();
        webLabel3 = new com.alee.laf.label.WebLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        webLabel4.setBackground(new java.awt.Color(240, 240, 240));
        webLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        webLabel4.setText("<html><p style=\"text-align:center\">\nWe are very passoinate about our enviroment &amp; thats <br/>\nwhy we have written this and all our application user manual<br/>\n in e-format.<br/>\nPlease download it/them at <a href=\"#\"> http://www.chieflabs.com/products</a><br/>\nLETS GO GREEN, LETS SAVE TREES!<br/>\nchieflabs &copy 2014.</p>\n");
        webLabel4.setFont(new java.awt.Font("Lao UI", 0, 10)); // NOI18N
        webLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        webLabel4.setIconTextGap(20);
        webLabel4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(webLabel4)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(webLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        webLabel3.setBackground(new java.awt.Color(240, 240, 240));
        webLabel3.setForeground(new java.awt.Color(255, 102, 0));
        webLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        webLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mynews/resources/paperless.png"))); // NOI18N
        webLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        webLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        webLabel3.setIconTextGap(20);
        webLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(webLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(webLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private com.alee.laf.label.WebLabel webLabel3;
    private com.alee.laf.label.WebLabel webLabel4;
    // End of variables declaration//GEN-END:variables
}
