/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mynews.ui;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextPane;
import mynews.utils.CustomScrollbarUI;

/**
 *
 * @author RESEARCH2
 */
public class JPanelArticles extends javax.swing.JPanel {

    /**
     * Creates new form JPanelArticles
     */
    public JPanelArticles() {
        initComponents();
        setJtextPane();
        jScrollPane2.getVerticalScrollBar().setPreferredSize(new Dimension(10, 0));
        jScrollPane2.getVerticalScrollBar().setUI(new CustomScrollbarUI(Color.WHITE));
    }

    public JLabel getjLabelImage() {
        return jLabelImage;
    }

    public void setjLabelImage(JLabel jLabelImage) {
        this.jLabelImage = jLabelImage;
    }

    public JTextPane getjTextPaneArticle() {
        return jTextPaneArticle;
    }

    public JButton getjButtonDelete() {
        return jButtonDelete;
    }

    public void setjButtonDelete(JButton jButtonDelete) {
        this.jButtonDelete = jButtonDelete;
    }

    public JButton getjButtonRead() {
        return jButtonRead;
    }

    public void setjButtonRead(JButton jButtonRead) {
        this.jButtonRead = jButtonRead;
    }

    public void setjTextPaneArticle(JTextPane jTextPaneArticle) {
        this.jTextPaneArticle = jTextPaneArticle;
    }

    private void setJtextPane() {
        jTextPaneArticle.setContentType("text/html");
        jTextPaneArticle.setText("<html><head></head>"
                + "<body>"
                + "<p style=\"margin-top: 0;font-family:Lao UI, Helvetica, Arial, Luxi Sans, sans-serif;color:#404040\">"
                + "</p>"
                + "</body>"
                + "</html>");
    }

    public JLabel getjLabelDate() {
        return jLabelDate;
    }

    public void setjLabelDate(JLabel jLabelDate) {
        this.jLabelDate = jLabelDate;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHolder = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneArticle = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelImage = new javax.swing.JLabel();
        jButtonDelete = new javax.swing.JButton();
        jButtonRead = new javax.swing.JButton();
        jLabelDate = new javax.swing.JLabel();

        jPanelHolder.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBorder(null);

        jTextPaneArticle.setBorder(null);
        jTextPaneArticle.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        jTextPaneArticle.setForeground(new java.awt.Color(51, 51, 51));
        jTextPaneArticle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextPaneArticleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextPaneArticleMouseExited(evt);
            }
        });
        jScrollPane2.setViewportView(jTextPaneArticle);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });

        jButtonDelete.setFont(new java.awt.Font("Lao UI", 0, 11)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(51, 51, 51));
        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mynews/resources/delete_32.png"))); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.setContentAreaFilled(false);
        jButtonDelete.setFocusPainted(false);
        jButtonDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDelete.setIconTextGap(0);
        jButtonDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonDeleteMouseExited(evt);
            }
        });
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonRead.setFont(new java.awt.Font("Lao UI", 0, 11)); // NOI18N
        jButtonRead.setForeground(new java.awt.Color(51, 51, 51));
        jButtonRead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mynews/resources/read.png"))); // NOI18N
        jButtonRead.setText("Read");
        jButtonRead.setContentAreaFilled(false);
        jButtonRead.setFocusPainted(false);
        jButtonRead.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRead.setIconTextGap(0);
        jButtonRead.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonReadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonReadMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonRead))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRead))
            .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabelDate.setBackground(new java.awt.Color(245, 245, 220));
        jLabelDate.setFont(new java.awt.Font("Lao UI", 0, 11)); // NOI18N
        jLabelDate.setForeground(new java.awt.Color(51, 51, 51));
        jLabelDate.setText("     Sep 12 2014 8:09");
        jLabelDate.setOpaque(true);

        javax.swing.GroupLayout jPanelHolderLayout = new javax.swing.GroupLayout(jPanelHolder);
        jPanelHolder.setLayout(jPanelHolderLayout);
        jPanelHolderLayout.setHorizontalGroup(
            jPanelHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHolderLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
            .addComponent(jLabelDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelHolderLayout.setVerticalGroup(
            jPanelHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHolderLayout.createSequentialGroup()
                .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanelHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHolder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        jTextPaneArticle.setBackground(Color.red);
        jPanelHolder.setBackground(Color.red);
        jPanel1.setBackground(Color.red);
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jTextPaneArticleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPaneArticleMouseEntered
        jTextPaneArticle.setBackground(new Color(154, 205, 50));
        jPanelHolder.setBackground(new Color(154, 205, 50));
        jPanel1.setBackground(new Color(154, 205, 50));
    }//GEN-LAST:event_jTextPaneArticleMouseEntered

    private void jTextPaneArticleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPaneArticleMouseExited
        jTextPaneArticle.setBackground(null);
        jPanelHolder.setBackground(null);
        jPanel1.setBackground(null);
    }//GEN-LAST:event_jTextPaneArticleMouseExited

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        jTextPaneArticle.setBackground(new Color(154, 205, 50));
        jPanelHolder.setBackground(new Color(154, 205, 50));
        jPanel1.setBackground(new Color(154, 205, 50));
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        jTextPaneArticle.setBackground(null);
        jPanelHolder.setBackground(null);
        jPanel1.setBackground(null);
    }//GEN-LAST:event_jPanel1MouseExited

    private void jButtonReadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReadMouseEntered
        jTextPaneArticle.setBackground(new Color(154, 205, 50));
        jPanelHolder.setBackground(new Color(154, 205, 50));
        jPanel1.setBackground(new Color(154, 205, 50));
    }//GEN-LAST:event_jButtonReadMouseEntered

    private void jButtonDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteMouseEntered
        jTextPaneArticle.setBackground(new Color(154, 205, 50));
        jPanelHolder.setBackground(new Color(154, 205, 50));
        jPanel1.setBackground(new Color(154, 205, 50));
    }//GEN-LAST:event_jButtonDeleteMouseEntered

    private void jButtonDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteMouseExited
        jTextPaneArticle.setBackground(null);
        jPanelHolder.setBackground(null);
        jPanel1.setBackground(null);
    }//GEN-LAST:event_jButtonDeleteMouseExited

    private void jButtonReadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReadMouseExited
        jTextPaneArticle.setBackground(null);
        jPanelHolder.setBackground(null);
        jPanel1.setBackground(null);
    }//GEN-LAST:event_jButtonReadMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonRead;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelHolder;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPaneArticle;
    // End of variables declaration//GEN-END:variables
}
